name: cms-mamba

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10.12
  - pytorch=2.5.0
  - pytorch-cuda=12.6
  - cudnn=9.3
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - numpy=1.26.4
  - scikit-learn=1.6.1
  - pyyaml=6.0.2
  - pip
  - pip:
      - causal-conv1d==1.4.0
      - einops==0.8.0
      - mamba-ssm==2.2.2
      - transformers==4.46.3
