base:
  seed: 2024
  lr: 0.0001
  weight_decay: 0.0001
  batch_size: 64
  n_epochs: 200
  num_workers: 8
  train_mode: regression
  do_validation: true
  validation_missing_rates: [0.0, 0.1, 0.5, 0.9, 1.0]
  validation_mask_seeds: [1111, 2222, 3333]
  missing_pattern: independent
  missing_rate_eval_test: 0.0
  eval_missing_modalities: TAV

dataset:
  datasetName: mosei
  dataPath: "./data/CMU_MOSEI/Processed/unaligned_50.pkl"

model:
  com_dim: &com_dim 128
  dropout: &dropout 0.2
  feature_extractor:
    bert_pretrained: "./bert-base-uncased"
  tmm:
    input_length: [50, 500, 500]
    input_dim: [768, 35, 74]
    hidden_dim: *com_dim
  tc_mamba:
    num_layers: 2
    d_model: *com_dim
    d_ffn: 1024
    activation: GELU
    dropout: *dropout
    causal: false
    dtf_threshold: 0.1
    mamba_config:
      d_state: 16
      expand: 4
      d_conv: 4
      bidirectional: true
  tq_mamba:
    num_layers: 2
    d_model: *com_dim
    d_ffn: 1024
    activation: GELU
    dropout: *dropout
    causal: false
    rope_base: 10000.0
    attn_heads: 8
    mamba_config:
      d_state: 16
      expand: 4
      d_conv: 4
      bidirectional: true
  regression:
    input_dim: *com_dim
    out_dim: 1
